#pragma once
// Ontologia: TRANSCRICAO (Segmento de legenda) e TRILHA DE LEGENDA.
#include <cstdint>
#include <string>
#include <vector>

namespace saci {

// Janela temporal de uma fala, vinda do SRT.
struct TranscriptSegment {
    std::size_t index = 0;
    std::int64_t start_ms = 0;
    std::int64_t end_ms = 0;
    std::string text;
    std::int64_t window_ms() const { return end_ms - start_ms; }
};

// "Kind": manual (criador) vs auto (STT do YouTube). Afeta confianca.
enum class SubtitleKind { Manual, AutoGenerated };

struct SubtitleTrack {
    std::string lang;          // ex. "en", "pt-BR"
    SubtitleKind kind = SubtitleKind::Manual;
    std::vector<TranscriptSegment> segments;
};

// parse "00:01:02,345" -> ms
std::int64_t srt_timestamp_to_ms(const std::string& ts);
std::vector<TranscriptSegment> parse_srt(const std::string& content);

} // namespace saci
